name: TStaffMode
main: com.tenth.tstaffmode.StaffMode
version: 1.1
api-version: 1.21.3
commands:
  tstaffmode:
    description: Toggle staff mode. Wipes user's inventory.
    usage: /tstaffmode <on|off>
    permission: tstaffmode.use
  help:
    description: Get plugin help and version.
    usage: /tstaffmode help
    permission: tstaffmode.use
permissions:
  staffmode.use:
    description: Allows usage of staffmode commands
    default: op
  staffmode.updater:
    description: Allow admins to give the plugin permission to pull from github new code to update versions.
    default: op